"""empty message

Revision ID: 17da67440d05
Revises: 086fc5ab1924
Create Date: 2017-06-03 21:34:06.456117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17da67440d05'
down_revision = '086fc5ab1924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_type', sa.Column('solution_max_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_type', 'solution_max_size')
    # ### end Alembic commands ###
