"""empty message

Revision ID: 1be5b55ecd31
Revises: 8c7e3a501eff
Create Date: 2017-06-09 18:30:46.476593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be5b55ecd31'
down_revision = '8c7e3a501eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('elapsed', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'elapsed')
    # ### end Alembic commands ###
