"""empty message

Revision ID: 2e917ada97a1
Revises: 58a8ae90bf15
Create Date: 2017-06-01 21:06:00.477015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e917ada97a1'
down_revision = '58a8ae90bf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('statistics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'statistics')
    # ### end Alembic commands ###
