"""empty message

Revision ID: 515d2606c301
Revises: 1be5b55ecd31
Create Date: 2017-06-09 19:45:19.002828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '515d2606c301'
down_revision = '1be5b55ecd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rods',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('rods', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], [u'board.id'], name=u'rods_board_id_fkey'),
    sa.PrimaryKeyConstraint('timestamp', 'board_id', name=u'rods_pkey')
    )
    # ### end Alembic commands ###
