"""empty message

Revision ID: 8c7e3a501eff
Revises: ca47fe9beded
Create Date: 2017-06-09 17:59:40.708637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7e3a501eff'
down_revision = 'ca47fe9beded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('paused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'paused')
    # ### end Alembic commands ###
