"""empty message

Revision ID: ca47fe9beded
Revises: 17da67440d05
Create Date: 2017-06-05 00:06:00.203792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca47fe9beded'
down_revision = '17da67440d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('actions', sa.String(), nullable=True))
    op.drop_column('event', 'details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('event', 'actions')
    # ### end Alembic commands ###
