"""empty message

Revision ID: cef86c33b763
Revises: 0abe26c0f269
Create Date: 2017-05-30 19:04:27.632120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef86c33b763'
down_revision = '0abe26c0f269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'activity_type_name_key', 'activity_type', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'activity_type_name_key', 'activity_type', ['name'])
    # ### end Alembic commands ###
